=== therealchalz/projector/projector.dtd
<!--
Copyright (c) 2015 Charles Hache <chalz@member.fsf.org>. All rights reserved. 

This file is part of the projector project.
projector is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

projector is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with projector.  If not, see <http://www.gnu.org/licenses/>.

Contributors:
    Charles Hache <chalz@member.fsf.org> - initial API and implementation
-->
<!ELEMENT projector (project,object*)>

<!ELEMENT project (name,projectPackage,rootElement,rootObject)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT projectPackage (#PCDATA)>
<!ELEMENT rootElement (#PCDATA)>
<!ELEMENT rootObject (#PCDATA)>

<!ELEMENT object (name,superclass?,field*,reference*)>
<!ELEMENT superclass (#PCDATA)>

<!ELEMENT field (name,elementName?,type,size,options?)>
<!ELEMENT elementName (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT options (option*)>
<!ELEMENT option (#PCDATA)>

<!ELEMENT reference (name,elementName?,targetType,relationship,subclassType*,options?)>
<!ELEMENT targetType (#PCDATA)>
<!ELEMENT relationship (#PCDATA)>
<!ELEMENT subclassType (elementName,targetType)>

=== therealchalz/projector/projectorOut.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE projector SYSTEM "projector.dtd">
<projector>
  <project>
    <rootElement>projector</rootElement>
    <rootObject>Projector</rootObject>
    <name>Projector</name>
    <projectPackage>ca.brood.projector</projectPackage>
  </project>
  <object>
    <name>Projector</name>
    <reference>
      <name>project</name>
      <targetType>ProjectorProject</targetType>
      <relationship>onetoone</relationship>
      <elementName>project</elementName>
    </reference>
    <reference>
      <name>projectObjects</name>
      <targetType>ProjectorObject</targetType>
      <relationship>onetomany</relationship>
      <elementName>object</elementName>
    </reference>
  </object>
  <object>
    <name>ProjectorProject</name>
    <field>
      <name>rootElement</name>
      <type>string</type>
      <size>512</size>
      <elementName>rootElement</elementName>
    </field>
    <field>
      <name>rootObject</name>
      <type>string</type>
      <size>512</size>
      <elementName>rootObject</elementName>
    </field>
    <field>
      <name>name</name>
      <type>string</type>
      <size>512</size>
      <elementName>name</elementName>
    </field>
    <field>
      <name>projectPackage</name>
      <type>string</type>
      <size>512</size>
      <elementName>projectPackage</elementName>
    </field>
  </object>
  <object>
    <name>ProjectorObject</name>
    <field>
      <name>name</name>
      <type>string</type>
      <size>255</size>
      <elementName>name</elementName>
    </field>
    <field>
      <name>superclass</name>
      <type>string</type>
      <size>255</size>
      <elementName>superclass</elementName>
    </field>
    <reference>
      <name>fields</name>
      <targetType>ProjectorField</targetType>
      <relationship>onetomany</relationship>
      <elementName>field</elementName>
    </reference>
    <reference>
      <name>references</name>
      <targetType>ProjectorReference</targetType>
      <relationship>onetomany</relationship>
      <elementName>reference</elementName>
    </reference>
  </object>
  <object>
    <name>ProjectorField</name>
    <field>
      <name>name</name>
      <type>string</type>
      <size>255</size>
      <elementName>name</elementName>
    </field>
    <field>
      <name>type</name>
      <type>string</type>
      <size>32</size>
      <elementName>type</elementName>
    </field>
    <field>
      <name>size</name>
      <type>integer</type>
      <size>4</size>
      <elementName>size</elementName>
    </field>
    <field>
      <name>elementName</name>
      <type>string</type>
      <size>255</size>
      <elementName>elementName</elementName>
    </field>
  </object>
  <object>
    <name>SubclassType</name>
    <field>
      <name>elementName</name>
      <type>string</type>
      <size>255</size>
      <elementName>elementName</elementName>
    </field>
    <field>
      <name>targetType</name>
      <type>string</type>
      <size>255</size>
      <elementName>targetType</elementName>
    </field>
  </object>
  <object>
    <name>ProjectorReference</name>
    <field>
      <name>name</name>
      <type>string</type>
      <size>255</size>
      <elementName>name</elementName>
    </field>
    <field>
      <name>targetType</name>
      <type>string</type>
      <size>255</size>
      <elementName>targetType</elementName>
    </field>
    <field>
      <name>relationship</name>
      <type>string</type>
      <size>255</size>
      <elementName>relationship</elementName>
    </field>
    <field>
      <name>elementName</name>
      <type>string</type>
      <size>255</size>
      <elementName>elementName</elementName>
    </field>
    <reference>
      <name>subclassTypes</name>
      <targetType>SubclassType</targetType>
      <relationship>onetomany</relationship>
      <elementName>subclassType</elementName>
    </reference>
  </object>
</projector>

=== therealchalz/projector/projector.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  Copyright (c) 2015 Charles Hache <chalz@member.fsf.org>. All rights reserved. 
  
  This file is part of the projector project.
  projector is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  projector is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with projector.  If not, see <http://www.gnu.org/licenses/>.
  
  Contributors:
      Charles Hache <chalz@member.fsf.org> - initial API and implementation
-->
<!DOCTYPE projector SYSTEM "projector.dtd">
<projector>
  <project>
    <name>Projector</name>
    <projectPackage>ca.brood.projector</projectPackage>
    <rootElement>projector</rootElement>
    <rootObject>Projector</rootObject>
  </project>
  <object>
    <name>Projector</name>
    <reference>
      <name>project</name>
      <elementName>project</elementName>
      <targetType>ProjectorProject</targetType>
      <relationship>onetoone</relationship>
    </reference>
    <reference>
      <name>projectObjects</name>
      <elementName>object</elementName>
      <targetType>ProjectorObject</targetType>
      <relationship>onetomany</relationship>
    </reference>
  </object>
  <object>
    <name>ProjectorProject</name>
    <field>
      <name>name</name>
      <elementName>name</elementName>
      <type>string</type>
      <size>512</size>
    </field>
    <field>
      <name>projectPackage</name>
      <elementName>projectPackage</elementName>
      <type>string</type>
      <size>512</size>
    </field>
    <field>
      <name>rootElement</name>
      <elementName>rootElement</elementName>
      <type>string</type>
      <size>512</size>
    </field>
    <field>
      <name>rootObject</name>
      <elementName>rootObject</elementName>
      <type>string</type>
      <size>512</size>
    </field>
  </object>
  <object>
    <name>ProjectorObject</name>
    <field>
      <name>name</name>
      <elementName>name</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <field>
      <name>superclass</name>
      <elementName>superclass</elementName>
      <type>string</type>
      <size>255</size>
	  <options>
		<option>optional</option>
	  </options>
    </field>
    <reference>
      <name>fields</name>
      <elementName>field</elementName>
      <targetType>ProjectorField</targetType>
      <relationship>onetomany</relationship>
    </reference>
    <reference>
      <name>references</name>
      <elementName>reference</elementName>
      <targetType>ProjectorReference</targetType>
      <relationship>onetomany</relationship>
    </reference>
  </object>
  <object>
    <name>ProjectorField</name>
    <field>
      <name>name</name>
      <elementName>name</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <field>
      <name>elementName</name>
      <elementName>elementName</elementName>
      <type>string</type>
      <size>255</size>
	  <options>
		<option>optional</option>
	  </options>
    </field>
    <field>
      <name>type</name>
      <elementName>type</elementName>
      <type>string</type>
      <size>32</size>
    </field>
    <field>
      <name>size</name>
      <elementName>size</elementName>
      <type>integer</type>
      <size>4</size>
    </field>
    <reference>
      <name>options</name>
      <elementName>options</elementName>
      <targetType>ProjectorOptions</targetType>
      <relationship>onetoone</relationship>
	  <options>
		<option>optional</option>
	  </options>
    </reference>
  </object>
  <object>
	<name>ProjectorOptions</name>
	<field>
		<name>options</name>
		<elementName>option</elementName>
		<type>string</type>
		<size>255</size>
		<options>
			<option>multiple</option>
		</options>
	</field>
  </object>
  <object>
    <name>SubclassType</name>
    <field>
      <name>elementName</name>
      <elementName>elementName</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <field>
      <name>targetType</name>
      <elementName>targetType</elementName>
      <type>string</type>
      <size>255</size>
    </field>
  </object>
  <object>
    <name>ProjectorReference</name>
    <field>
      <name>name</name>
      <elementName>name</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <field>
      <name>elementName</name>
      <elementName>elementName</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <field>
      <name>targetType</name>
      <elementName>targetType</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <field>
      <name>relationship</name>
      <elementName>relationship</elementName>
      <type>string</type>
      <size>255</size>
    </field>
    <reference>
      <name>subclassTypes</name>
      <elementName>subclassType</elementName>
      <targetType>SubclassType</targetType>
      <relationship>onetomany</relationship>
    </reference>
	<reference>
      <name>options</name>
      <targetType>ProjectorOptions</targetType>
      <relationship>onetoone</relationship>
	  <options>
		<option>optional</option>
	  </options>
    </reference>
  </object>
</projector>

=== therealchalz/projector/sampleproject.xml
<!DOCTYPE projector SYSTEM "projector.dtd"><projector>	<project>		<name>Softlogger</name>		<projectPackage>ca.brood.softlogger</projectPackage>		<rootElement>softlogger</rootElement>		<rootObject>Softlogger</rootObject>	</project>	<object>		<name>Softlogger</name>		<field>			<name>name</name>			<type>string</type>			<size>255</size>		</field>		<field>			<name>poll</name>			<type>integer</type>			<size>4</size>		</field>		<field>			<name>tableFilePath</name>			<type>string</type>			<size>255</size>		</field>		<field>			<name>dataFilePath</name>			<type>string</type>			<size>255</size>		</field>				<reference>			<name>dataServer</name>			<elementName>server</elementName>			<targetType>DataServer</targetType>			<relationship>onetoone</relationship>		</reference>		<reference>			<name>softloggerChannels</name>			<elementName>channel</elementName>			<targetType>SoftloggerChannel</targetType>			<relationship>onetomany</relationship>		</reference>	</object>	<object>		<name>DataServer</name>		<field>			<name>host</name>			<type>string</type>			<size>255</size>		</field>		<field>			<name>user</name>			<type>string</type>			<size>255</size>		</field>		<field>			<name>configPoll</name>			<type>integer</type>			<size>4</size>		</field>		<field>			<name>path</name>			<type>string</type>			<size>255</size>		</field>		<field>			<name>password</name>			<type>string</type>			<size>255</size>		</field>		<field>			<name>keyfile</name>			<type>string</type>			<size>255</size>		</field>	</object>	<object>		<name>SoftloggerChannel</name>		<reference>			<name>modbusChannel</name>			<targetType>ModbusChannel</targetType>			<subclassType>				<elementName>tcp</elementName>				<targetType>ModbusTcpChannel</targetType>			</subclassType>			<relationship>onetoone</relationship>		</reference>	</object>	<object>		<name>ModbusChannel</name>		<field>			<name>poll</name>			<type>integer</type>			<size>4</size>		</field>	</object>	<object>		<name>ModbusTcpChannel</name>		<superclass>ModbusChannel</superclass>		<field>			<name>port</name>			<type>integer</type>			<size>2</size>		</field>		<field>			<name>host</name>			<type>string</type>			<size>255</size>		</field>	</object></projector>

=== therealchalz/projector/sampleprojectOut.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE projector SYSTEM "projector.dtd">
<projector>
  <project>
    <rootElement>softlogger</rootElement>
    <rootObject>Softlogger</rootObject>
    <name>Softlogger</name>
    <projectPackage>ca.brood.softlogger</projectPackage>
  </project>
  <object>
    <name>Softlogger</name>
    <field>
      <name>name</name>
      <type>string</type>
      <size>255</size>
      <elementName>name</elementName>
    </field>
    <field>
      <name>poll</name>
      <type>integer</type>
      <size>4</size>
      <elementName>poll</elementName>
    </field>
    <field>
      <name>tableFilePath</name>
      <type>string</type>
      <size>255</size>
      <elementName>tableFilePath</elementName>
    </field>
    <field>
      <name>dataFilePath</name>
      <type>string</type>
      <size>255</size>
      <elementName>dataFilePath</elementName>
    </field>
    <reference>
      <name>dataServer</name>
      <targetType>DataServer</targetType>
      <relationship>onetoone</relationship>
      <elementName>server</elementName>
    </reference>
    <reference>
      <name>softloggerChannels</name>
      <targetType>SoftloggerChannel</targetType>
      <relationship>onetomany</relationship>
      <elementName>channel</elementName>
    </reference>
  </object>
  <object>
    <name>DataServer</name>
    <field>
      <name>user</name>
      <type>string</type>
      <size>255</size>
      <elementName>user</elementName>
    </field>
    <field>
      <name>host</name>
      <type>string</type>
      <size>255</size>
      <elementName>host</elementName>
    </field>
    <field>
      <name>password</name>
      <type>string</type>
      <size>255</size>
      <elementName>password</elementName>
    </field>
    <field>
      <name>keyfile</name>
      <type>string</type>
      <size>255</size>
      <elementName>keyfile</elementName>
    </field>
    <field>
      <name>configPoll</name>
      <type>integer</type>
      <size>4</size>
      <elementName>configPoll</elementName>
    </field>
    <field>
      <name>path</name>
      <type>string</type>
      <size>255</size>
      <elementName>path</elementName>
    </field>
  </object>
  <object>
    <name>SoftloggerChannel</name>
    <reference>
      <name>modbusChannel</name>
      <targetType>ModbusChannel</targetType>
      <relationship>onetoone</relationship>
      <elementName>modbusChannel</elementName>
      <subclassType>
        <elementName>tcp</elementName>
        <targetType>ModbusTcpChannel</targetType>
      </subclassType>
    </reference>
  </object>
  <object>
    <name>ModbusChannel</name>
    <field>
      <name>poll</name>
      <type>integer</type>
      <size>4</size>
      <elementName>poll</elementName>
    </field>
  </object>
  <object>
    <name>ModbusTcpChannel</name>
    <superclass>ModbusChannel</superclass>
    <field>
      <name>host</name>
      <type>string</type>
      <size>255</size>
      <elementName>host</elementName>
    </field>
    <field>
      <name>port</name>
      <type>integer</type>
      <size>2</size>
      <elementName>port</elementName>
    </field>
  </object>
</projector>
